id = "technique"
name = "Technique"
description = "Syntax highlighting for the Technique procedure language"
version = "0.2.6"
schema_version = 1
authors = ["Andrew Cowie"]
repository = "https://github.com/technique-lang/extension.zed"

[grammars.technique]
repository = "https://github.com/technique-lang/tree-sitter-technique"
commit = "199af14af6c3711ba02e3551a9448c71e4245e5c"

[language_servers.technique]
name = "technique"
languages = ["Technique"]
