id = "technique"
name = "Technique"
description = "Syntax highlighting for the Technique procedure language"
version = "0.2.8"
schema_version = 1
authors = ["Andrew Cowie"]
repository = "https://github.com/technique-lang/extension.zed"

[grammars.technique]
repository = "https://github.com/technique-lang/tree-sitter-technique"
commit = "01e2fcffb3d86a5600552f6ece575447d5ae523e"

[language_servers.technique]
name = "technique"
languages = ["Technique"]
